### ISSUE TITLE
Slight tweaks to 'Component.spec.js' file

### ISSUE THREAD

**Issue by Salstar24** [zishan-ali/tyler#12]
**Describe the bug**
Just used Tyler to generate a new Template in Pages Lib - nice!

I've noticed a couple of things which could change in the default set-up for the `Component.spec.js` file:

1) It uses `shallow` rather than `mount` from enzyme.
2) It uses `test` rather than `it` for unit tests (`it` was agreed as the convention :) )

**Comment by zishan-ali** [comment]
Just added support for recipes, meaning we can change what the CLI outputs for a particular file through these, they can be found in the `recipes` directory under each atomic package 😄
